name = "tendergo-backend"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[d1_databases]]
binding = "DB"
database_name = "tendergo-db"
database_id = "3da49154-e2a9-4564-965e-ed3e3709de49"
migrations_dir = "migrations"

[vars]
CORS_ORIGIN = "https://tendergo-taiwan.pages.dev"
PCC_BASE_URL = "https://web.pcc.gov.tw"

[dev]
port = 3000
ip = "0.0.0.0"
